eureka:
  client:
    service-url:  #EurekaServer 地址  # 下面指向的是注册中心的defaultZone
     defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 30 #并且每隔30秒会重新获取并更新数据。

spring:
  application:
    name: user-consumer
server:
  port: 8080
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能


logging:
  level:
    cn.itcast: debug
