server:
  port: 8081
spring:
    application:
      name: user-service
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: hmj050117
logging:
  level:
    cn.itcast.controller: debug
eureka:
  client:
    service-url:  #EurekaServer 地址  # 下面指向的是注册中心的defaultZone
     defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: true  #是否注册给eureka容器，默认是true
    fetch-registry: false     #是否拉取服务列表，默认是ture
    registry-fetch-interval-seconds: 30 #拉取服务的间隔时间，默认30秒
  instance:
    ip-address: 127.0.0.1  #ip地址
    prefer-ip-address: true  # 更倾向于使用ip，而不是host名
    lease-expiration-duration-in-seconds: 90   #服务(过期)失效时间，默认值90秒
    lease-renewal-interval-in-seconds: 30     #心跳(续约)时间默认为30秒