server:
  port: 8081
spring:
    application:
      name: user-service
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: hmj050117
logging:
  level:
    cn.itcast.controller: debug
eureka:
  client:
    service-url:  #EurekaServer 地址  # 下面指向的是注册中心的defaultZone
     defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1  #ip地址
    prefer-ip-address: true  # 更倾向于使用ip，而不是host名
    lease-expiration-duration-in-seconds: 90   #服务失效时间，默认值90秒
    lease-renewal-interval-in-seconds: 30     #服务续约(renew)的间隔，默认为30秒